"""MCP toolset loader for the business-analysis agent.

Loads:
    1. The agent's own MCP server (URL from MCP_BA_URL env var, defaults
       to costaff-mcp-business-analysis:8083). Authorization header is
       attached using MCP_SECRET_KEY.
    2. Any extra MCP servers configured via BUSINESS_ANALYSIS_AGENT_MCP_URLS
       (set by the CoStaff dashboard at deploy time).

Usage:
    from mcp_toolsets import load_all_mcp_toolsets
    toolsets = load_all_mcp_toolsets()  # list of McpToolset
"""
import json
import logging
import os
from typing import List

from google.adk.tools.mcp_tool import McpToolset
from google.adk.tools.mcp_tool.mcp_session_manager import StreamableHTTPServerParams

logger = logging.getLogger(__name__)

DEFAULT_MCP_URL = "http://costaff-mcp-business-analysis:8083/mcp"


def _connection_params(entry):
    """Coerce an entry (string URL or dict) into StreamableHTTPServerParams."""
    if isinstance(entry, str):
        url, headers = entry, None
    else:
        url = entry.get("url", "")
        headers = entry.get("headers") or None
    if not url:
        raise ValueError("MCP entry has no URL")
    return StreamableHTTPServerParams(url=url, headers=headers)


def load_all_mcp_toolsets() -> List[McpToolset]:
    """Build the agent's MCP toolset list from env configuration."""
    toolsets: List[McpToolset] = []

    # Own MCP — always connected, with bearer auth
    own_url = os.getenv("MCP_BA_URL", DEFAULT_MCP_URL)
    mcp_token = os.getenv(
        "MCP_SECRET_KEY",
        "REDACTED",
    )
    own_params = StreamableHTTPServerParams(
        url=own_url,
        headers={"Authorization": f"Bearer {mcp_token}"},
    )
    toolsets.append(McpToolset(connection_params=own_params))
    logger.info(f"Business Analysis MCP URL: {own_url}")

    # Extra-MCP block is intentionally DISABLED.
    #
    # BUSINESS_ANALYSIS_AGENT_MCP_URLS (auto-generated by the CoStaff
    # dashboard) contains the full MCP_SERVER_URLS map: costaff, coding,
    # twinkle-hub, AND business-analysis itself. Connecting to any of
    # these opens additional MCP ClientSessions, and EVERY extra session
    # multiplies the chance of the anyio CancelScope cross-task race
    # (google/adk-python#4454, no fix on ADK 1.33) that silently strips
    # this agent of its tools.
    #
    # BA only ever needs ONE MCP: its own (loaded above via own_params).
    #   - manager-core's 4 shared tools → now via the plain-HTTP shim
    #     (agent/tools/costaff_api.py), no MCP session, race-free.
    #   - other agents' MCPs (coding/twinkle) → never needed by BA.
    #   - the self-referential "business-analysis" extra entry → a
    #     duplicate of own_params; connecting again = 2 sessions = race.
    #
    # So we deliberately do NOT iterate the extra config. Re-enable only
    # if a genuine, non-duplicate extra MCP is ever required AND the
    # upstream cancel-scope race is fixed.
    raw_extra = os.getenv("BUSINESS_ANALYSIS_AGENT_MCP_URLS", "")
    if raw_extra:
        logger.info(
            "Extra-MCP block disabled (race avoidance): BA uses only its "
            "own MCP + native HTTP wrappers for the 4 shared tools."
        )

    return toolsets
